channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - demoji
  - networkx
  - pandas
  - polyleven
  - requests
  - tqdm
  - numpy
  - scikit-learn
  - pip:
      - git+https://github.com/savaij/astrodetection.git
