channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - demoji
  - faiss-cpu
  - fasttext
  - gensim
  - networkx
  - pandas
  - polyleven
  - scipy
  - requests
  - tqdm
  - pip
  - pip:
      - git+https://github.com/savaij/astrodetection.git
      - ipysigma